config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires do
    resources :sections, only: [:new, :create]
  end

  resources :sections, only: [] do
    resources :questions, only: [:new, :create]
  end

  root 'questionnaires#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :section

  scope :persisted, -> { where.not(id: nil) }
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :sections, dependent: :destroy
  accepts_nested_attributes_for :sections, reject_if: :all_blank
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :questionnaire
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, reject_if: :all_blank

  scope :persisted, -> { where.not(id: nil) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[ show edit update destroy ]

  # GET /questionnaires
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to questionnaire_url(@questionnaire) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to questionnaire_url(@questionnaire) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1
  def destroy
    @questionnaire.destroy

    respond_to do |format|
      format.html { redirect_to questionnaires_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def questionnaire_params
      params.require(:questionnaire).permit(:name, sections_parameters: [:id, :name])
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_section, only: %i[ new create ]

  # GET /questions/new
  def new
    @question = @section.questions.build
  end

  # POST /questions
  def create
    @question = @section.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @section.questionnaire }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:section_id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_questionnaire, only: %i[ new create ]

  # GET /sections/new
  def new
    @section = @questionnaire.sections.build
  end

  # POST /sections
  def create
    @section = @questionnaire.sections.build(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @questionnaire }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:questionnaire_id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:name, questions_params: [:id, :question])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container pt-5">
      <%= flash_messages %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/questionnaires/_form.html.erb
<%= bootstrap_form_with(model: questionnaire) do |form| %>
    <%= form.text_field :name %>
    <%= form.primary %>
<%- end -%>

app/views/questionnaires/_questionnaire.html.erb
<div id="<%= dom_id questionnaire %>">
  <p>
    <%= link_to questionnaire.name, questionnaire %>
  </p>
</div>

app/views/questionnaires/edit.html.erb
<h1>Editing questionnaire</h1>

<%= render "form", questionnaire: @questionnaire %>

<div class="btn-group">
  <%= link_to "Show this questionnaire", @questionnaire, class: 'btn btn-secondary' %>
  <%= link_to "Back to questionnaires", questionnaires_path, class: 'btn btn-info' %>
</div>

app/views/questionnaires/index.html.erb
<h1>Questionnaires</h1>

<div id="questionnaires">
  <%= render @questionnaires %>
</div>

<%= link_to "New questionnaire", new_questionnaire_path, class: 'btn btn-primary' %>

app/views/questionnaires/new.html.erb
<h1>New questionnaire</h1>

<%= render "form", questionnaire: @questionnaire %>

<div class="btn-group">
  <%= link_to "Back to questionnaires", questionnaires_path, class: 'btn btn-info' %>
</div>

app/views/questionnaires/show.html.erb
<%= turbo_frame_tag @questionnaire do %>
  <%= tag.h1 @questionnaire.name %>
  <%= turbo_frame_tag @questionnaire, :sections do %>
    <%= render @questionnaire.sections %>
    <div class="my-3"><%= link_to 'Add a section', new_questionnaire_section_path(@questionnaire), class: 'btn btn-primary' %></div>
  <%- end -%>
<%- end -%>

<div class="btn-group form-btn-group">
  <%= link_to "Edit this questionnaire", edit_questionnaire_path(@questionnaire), class: 'btn btn-secondary' %>
  <%= link_to "Back to questionnaires", questionnaires_path, class: 'btn btn-info' %>
  <%= button_to "Destroy this questionnaire", @questionnaire, method: :delete, class: 'btn', form_class: 'btn btn-danger' %>
</div>

app/views/questions/_form.html.erb
<%= bootstrap_form_with(model: question, url: section_questions_path(question.section)) do |form| %>
  <%= form.text_field :question %>

  <%= form.primary %>
<%- end -%>

app/views/questions/_question.html.erb
<li id="<%= dom_id question %>">
    <%= question.question %>
</li>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= turbo_frame_tag @question.section, :questions do %>
  <div class="card-body">
      <ul>
        <%= render @section.questions.persisted %>
      </ul>
    <%= render "form", question: @question %>
  </div>
<%- end -%>

<div class="btn-group">
  <%= link_to "Back to questions", @question.section.questionnaire, class: 'btn btn-info' %>
</div>

app/views/sections/_form.html.erb
<%= bootstrap_form_with(model: section, url: questionnaire_sections_path(section.questionnaire), class: 'mb-3') do |form| %>
  <%= form.text_field :name %>

  <%= form.primary %>
<%- end -%>

app/views/sections/_section.html.erb
<div class="card mb-3" id="<%= dom_id section %>">
  <p class="card-header">
    <strong>Section:</strong>
    <%= section.name %>
  </p>
  <%= turbo_frame_tag section, :questions do %>
    <div class="card-body">
      <ul>
        <%= render section.questions %>
      </ul>
    </div>
    <div class="card-footer">
      <%= link_to 'Add a question', new_section_question_path(section), class: 'btn btn-success btn-sm' %>
    </div>
  <%- end -%>
</div>

app/views/sections/new.html.erb
<%= turbo_frame_tag @questionnaire, :sections do %>
<%= render @questionnaire.sections.persisted %>
<%= render "form", section: @section %>
<%- end -%>